### ISSUE TITLE
Problem with angular universal

### ISSUE THREAD

**Issue by alyeldegwy** [webcat12345/ngx-ui-switch#168] opened 2017-09-11 14:47 UTC
/home/XXX/Projects/XXXX/node_modules/ngx-ui-switch/src/index.ts:1
(function (exports, require, module, __filename, __dirname) { import { NgModule } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/XXX/Projects/XXXX/node_modules/ts-node/src/index.ts:376:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by cmckni3** [comment] 2017-10-02 21:50
Should be fixed in PR. I am sure the problem is related to not being built using ngc.

**Closed** 2017-10-12 21:38 UTC
