### ISSUE TITLE
Metadata version mismatch for module

### ISSUE THREAD

**Issue by SKrudra** [webcat12345/ngx-ui-switch#221] opened 2018-01-05 15:52 UTC
I'm trying to integrate it with my angular4 app with below dependencies:

`  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "ag-grid": "^14.2.0",
    "ag-grid-angular": "^14.2.0",
    "ag-grid-enterprise": "^14.2.0",
    "angular2-notifications": "^0.4.53",
    "bootstrap": "4.0.0-alpha.6",
    "core-js": "^2.4.1",
    "immutable": "^3.8.2",
    "jquery": "^3.2.1",
    "ngx-bootstrap": "^1.9.3",
    "ngx-ui-switch": "^1.3.0",
    "popper.js": "^1.12.9",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },`

But, I'm unable to build the project. Please find the error below:

> ERROR in Metadata version mismatch for module C:/.../node_modules/ngx-ui-switch/index.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/.../src/app/app.module.ts, resolving symbol AppModule in C:/.../src/main/webapp2.x/crossdock/src/app/app.module.ts

getting the same error with ngx-ui-switch@1.4.9

Any help would be appreciated.

**Comment by cmckni3** [comment] 2018-01-05 16:28
Duplicate of #219

**Closed by cmckni3** 2018-01-05 16:28 UTC
